<?xml version="1.0" encoding="utf-8"?><Database Name="db_news" Class="DbNewsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=AN;Initial Catalog=db_news;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="db_newsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[user]" Member="user">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="nickname" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="user_news" Member="news" ThisKey="id" OtherKey="userId" Type="news" />
      <Association Name="user_comment" Member="comment" ThisKey="id" OtherKey="userId" Type="comment" />
    </Type>
  </Table>
  <Table Name="dbo.category" Member="category">
    <Type Name="category">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Association Name="category_news" Member="news" ThisKey="id" OtherKey="categoryId" Type="news" />
    </Type>
  </Table>
  <Table Name="dbo.news" Member="news">
    <Type Name="news">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="categoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="summary" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="news_comment" Member="comment" ThisKey="id" OtherKey="newsId" Type="comment" />
      <Association Name="category_news" Member="category" ThisKey="categoryId" OtherKey="id" Type="category" IsForeignKey="true" />
      <Association Name="user_news" Member="user" ThisKey="userId" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.comment" Member="comment">
    <Type Name="comment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="newsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="news_comment" Member="news" ThisKey="newsId" OtherKey="id" Type="news" IsForeignKey="true" />
      <Association Name="user_comment" Member="user" ThisKey="userId" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
</Database>